services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  JingdongCrmBundle\Command\:
    resource: '../../Command/'
    exclude: '../../Command/.gitignore'
  JingdongCrmBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    exclude: '../../EventSubscriber/.gitignore'
  JingdongCrmBundle\Repository\:
    resource: '../../Repository/'
    exclude: '../../Repository/.gitignore'
  JingdongCrmBundle\Service\:
    resource: '../../Service/'
    exclude: '../../Service/.gitignore'
